
train_data_dir: './new_train/'
valid_data_dir: './new_train/'
test_data_dir: './new_train/'
max_len: 10
num_layers: 2
num_heads: 8
input_embedding_size: 32
num_units: 32
filters: 64
cnn_kernel_sizes: 3
learning_rate: 0.0002
batch_size: 3
devices: 2
dropout: 0.2
epoches: 128
decay: 0.0005
beta_1: 0.9
O_decayweight: 0.8
update_weight: 0.2
prob: 1
pretrain_path: 
valid_batch_size: 2
test_batch_size: 2